name: content modified

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write

jobs:
  rebuild:
    name: rebuild the site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: npm ci

      - name: build pages
        env:
          BASEURL: /pottery-projects
        run: npx @11ty/eleventy
      
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: _site

      - name: deploy
        uses: actions/deploy-pages@v1
